### ISSUE TITLE
Website Edition

### ISSUE THREAD

**Issue by voidlynx** [Bowlingtoolkit/hypesquad-changer#2]
If you people need a website version of the house changer, i can try and make it :D

**Comment by REVENGE977** [comment]
This is not a issue :/

**Comment by REVENGE977** [comment]
Also if you will make one that would be good fork the repository and make it if you want .

**Comment by voidlynx** [comment]
now 1.5yrs later i think what the hell did i write, how could even a website version of this be possible

**Comment by Ximaz** [comment]
> now 1.5yrs later i think what the hell did i write, how could even a website version of this be possible

You would have to prompt for user's token lmao.
